import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/marketing";

export const Route = createFileRoute("/faq")({ head: () => ({ meta: [{ title: "Frequently Asked Questions | Samrik Solutions" }, { name: "description", content: "Answers about Samrik Solutions sales services, industries, lead generation, and partnership options." }, { property: "og:title", content: "Frequently Asked Questions | Samrik Solutions" }, { property: "og:description", content: "Learn how Samrik Solutions supports startups and growing businesses." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/faq" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/faq" }] }), component: FAQ });
const faqs = [{ q: "What does Samrik Solutions do?", a: "Samrik Solutions provides sales and business-development support for SaaS, logistics, education, and other businesses." }, { q: "What industries do you specialize in?", a: "Our primary focus areas are SaaS, logistics, and education." }, { q: "Do you work with startups?", a: "Yes. We can work with startups and growing businesses looking to expand their customer base." }, { q: "Can you support lead generation?", a: "Yes. Lead generation and customer outreach can be part of our sales support services." }, { q: "Do you provide customized sales solutions?", a: "Yes. Sales solutions can be structured according to a client's industry, target customers, and business objectives." }, { q: "How can I partner with Samrik Solutions?", a: "You can submit the Partner With Us form or contact our team directly." }, { q: "How can I contact Samrik Solutions?", a: "Use the Contact Us page or the contact information displayed in the website footer." }];
function FAQ() { return <><PageHero eyebrow="Support" title="Frequently Asked Questions" description="Clear answers about our sales support, industry focus, and ways to work with Samrik Solutions." /><section className="py-20 md:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[1fr_2fr]"><aside><h2 className="font-display text-2xl font-bold">Need more information?</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Our team can discuss your specific industry, audience, and sales goals.</p><Button asChild variant="accent" className="mt-6"><Link to="/contact">Contact Us <ArrowRight /></Link></Button></aside><Accordion type="single" collapsible className="border-t border-border">{faqs.map((faq, index) => <AccordionItem key={faq.q} value={`item-${index}`}><AccordionTrigger className="py-6 font-display text-base font-bold no-underline hover:no-underline">{faq.q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 text-base leading-7 text-muted-foreground">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></div></section></>; }
