import { createFileRoute } from "@tanstack/react-router";
import { Boxes, BriefcaseBusiness, Building2, GraduationCap, Handshake, Rocket, School, ShieldCheck, Target, Workflow } from "lucide-react";
import { PartnershipForm } from "@/components/forms";
import { IconCard, PageHero, SectionHeading } from "@/components/marketing";

export const Route = createFileRoute("/partner")({ head: () => ({ meta: [{ title: "Partner With Us | Samrik Solutions" }, { name: "description", content: "Partner with Samrik Solutions to expand your customer base, strengthen sales capabilities, and reach new markets." }, { property: "og:title", content: "Let's Grow Together | Samrik Solutions" }, { property: "og:description", content: "A flexible, reliable sales partnership aligned with your business requirements." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/partner" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/partner" }] }), component: Partner });

const audiences = [[Boxes, "SaaS Companies"], [Building2, "Logistics Companies"], [GraduationCap, "EdTech Companies"], [School, "Educational Institutions"], [BriefcaseBusiness, "Training Organizations"], [Rocket, "Startups"], [Target, "Growing Businesses"]] as const;
function Partner() { return <><PageHero eyebrow="Partner With Us" title="Let's Grow Together" description="Looking for a reliable sales partner to help expand your customer base and market reach? Partner with Samrik Solutions." /><section className="py-20 md:py-28"><div className="section-shell"><SectionHeading eyebrow="Who We Support" title="Built for Ambitious Organizations" align="center" /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{audiences.map(([Icon, title]) => <article key={title} className="flex items-center gap-4 border border-border bg-card p-5 shadow-sm"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-accent text-accent-foreground"><Icon className="size-5" /></span><h3 className="font-display text-sm font-bold">{title}</h3></article>)}</div></div></section><section className="bg-surface py-20 md:py-28"><div className="section-shell"><SectionHeading eyebrow="Partnership Benefits" title="Why Partner With Samrik Solutions?" /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><IconCard icon={Target} title="Expand Your Reach">Reach new potential customers and markets.</IconCard><IconCard icon={ShieldCheck} title="Reduce Sales Pressure">Extend your sales capabilities with a dedicated sales partner.</IconCard><IconCard icon={Workflow} title="Flexible Engagement">Create a partnership model based on your business requirements.</IconCard><IconCard icon={Handshake} title="Focus on Your Core Business">Let your internal team focus on product and operations while we support sales activities.</IconCard></div></div></section><section className="py-20 md:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><SectionHeading eyebrow="Start a Conversation" title="Tell us what growth looks like for your business." description="Share your goals and current requirements. We’ll use the information to understand where our sales support can add the most value." /><div className="border border-border bg-card p-6 shadow-sm md:p-9"><PartnershipForm /></div></div></section></>; }
