import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Boxes, Building2, GraduationCap, Megaphone, Search, Target, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTASection, CheckList, IconCard, PageHero, SectionHeading } from "@/components/marketing";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [{ title: "Sales Solutions | Samrik Solutions" }, { name: "description", content: "Explore SaaS, logistics, education, lead generation, and business development sales solutions." }, { property: "og:title", content: "Our Sales Solutions | Samrik Solutions" }, { property: "og:description", content: "Industry-focused solutions for opportunity generation, customer acquisition, and market expansion." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/services" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/services" }] }), component: Services });

const detailed = [
  { icon: Boxes, title: "SaaS Sales Solutions", text: "Samrik Solutions supports SaaS businesses in reaching potential customers and creating new sales opportunities.", items: ["Lead generation", "Prospect identification", "Customer outreach", "Sales qualification", "Appointment setting", "Product/service communication", "Customer follow-up", "Sales pipeline support", "Customer relationship development"], cta: "Discuss Your SaaS Sales Needs" },
  { icon: Building2, title: "Logistics Sales Solutions", text: "We help logistics and supply-chain businesses connect with potential customers and identify new business opportunities.", items: ["B2B lead generation", "Customer prospecting", "Client outreach", "Business development", "Sales follow-up", "Client relationship management", "Market expansion support", "Opportunity identification"], cta: "Grow Your Logistics Business" },
  { icon: GraduationCap, title: "Educational Sales Solutions", text: "Samrik Solutions supports educational institutions, EdTech businesses, training providers, and learning organizations in reaching prospective students and customers.", items: ["Student lead generation", "Course promotion", "Admission/enrollment support", "Lead qualification", "Prospect engagement", "Follow-up", "Customer communication", "Education product sales"], cta: "Grow Your Education Business" },
] as const;

function Services() { return <><PageHero eyebrow="All Services" title="Our Sales Solutions" description="Explore our industry-focused sales solutions designed to help businesses generate opportunities, acquire customers, and expand their market presence." /><section className="py-20 md:py-28"><div className="section-shell space-y-16">{detailed.map((service, index) => <article key={service.title} className="grid gap-10 border-b border-border pb-16 lg:grid-cols-[0.85fr_1.15fr]"><div><span className="grid size-14 place-items-center rounded-md bg-primary text-primary-foreground"><service.icon /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-secondary">Service 0{index + 1}</p><h2 className="mt-3 font-display text-3xl font-bold">{service.title}</h2><p className="mt-5 leading-8 text-muted-foreground">{service.text}</p><Button asChild variant="accent" size="lg" className="mt-7"><Link to="/partner">{service.cta} <ArrowRight /></Link></Button></div><div className="bg-surface p-7 md:p-9"><h3 className="mb-6 font-display text-lg font-bold">What we can support</h3><CheckList items={service.items} /></div></article>)}</div></section><section className="bg-surface py-20 md:py-28"><div className="section-shell"><SectionHeading eyebrow="Additional Support" title="Flexible Sales Capabilities" description="Targeted support that strengthens your existing sales and business-development efforts." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><IconCard icon={Search} title="Lead Generation">Identify and connect businesses with relevant prospects.</IconCard><IconCard icon={TrendingUp} title="Business Development">Support organizations in identifying new opportunities and markets.</IconCard><IconCard icon={Target} title="Customer Acquisition">Help businesses create structured customer acquisition processes.</IconCard><IconCard icon={Megaphone} title="Sales Outreach">Professional communication and engagement with potential customers.</IconCard></div></div></section><CTASection /></>; }
