import { Body, Container, Head, Heading, Hr, Html, Section, Text } from '@react-email/components'
import type { TemplateEntry } from './registry'

export interface EnquiryNotificationProps {
  formType?: string
  rows?: Array<{ label: string; value: string }>
}

function EnquiryNotification({ formType = 'Contact Form', rows = [] }: EnquiryNotificationProps) {
  return (
    <Html>
      <Head />
      <Body style={{ backgroundColor: '#f4f6f8', fontFamily: 'Arial, sans-serif', margin: 0, padding: '24px 0' }}>
        <Container style={{ backgroundColor: '#ffffff', border: '1px solid #e2e8f0', maxWidth: '560px', margin: '0 auto', padding: '32px' }}>
          <Heading style={{ color: '#0b1f3a', fontSize: '20px', margin: '0 0 8px' }}>
            New {formType} Enquiry
          </Heading>
          <Text style={{ color: '#5b6b7f', fontSize: '14px', margin: '0 0 24px' }}>
            A new enquiry was submitted on the Samrik Solutions website.
          </Text>
          <Hr style={{ borderColor: '#e2e8f0', margin: '0 0 16px' }} />
          {rows.map((row) => (
            <Section key={row.label} style={{ marginBottom: '12px' }}>
              <Text style={{ color: '#5b6b7f', fontSize: '12px', fontWeight: 'bold', letterSpacing: '0.04em', margin: '0 0 2px', textTransform: 'uppercase' }}>
                {row.label}
              </Text>
              <Text style={{ color: '#0b1f3a', fontSize: '14px', margin: 0, whiteSpace: 'pre-wrap' }}>
                {row.value}
              </Text>
            </Section>
          ))}
          <Hr style={{ borderColor: '#e2e8f0', margin: '24px 0 16px' }} />
          <Text style={{ color: '#8a97a8', fontSize: '12px', margin: 0 }}>
            This message was generated by the Samrik Solutions website. Reply directly to respond to the sender.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: EnquiryNotification,
  subject: (data: Record<string, any>) => `New ${data.formType ?? 'Website'} Enquiry — ${data.name ?? 'Samrik Solutions'}`,
  displayName: 'Enquiry notification (to Samrik Solutions)',
  to: 'info@samrik.co.in',
  previewData: {
    formType: 'Contact Form',
    name: 'Priya Sharma',
    rows: [
      { label: 'Full Name', value: 'Priya Sharma' },
      { label: 'Company', value: 'Acme Logistics' },
      { label: 'Email', value: 'priya@example.com' },
      { label: 'Phone', value: '+91 90000 00000' },
      { label: 'Message', value: 'We would like to discuss logistics sales support for our business.' },
    ],
  },
} satisfies TemplateEntry
