/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesEducationalServicesRouteImport } from './routes/services.educational-services'
import { Route as ServicesLogisticsSalesRouteImport } from './routes/services.logistics-sales'
import { Route as ServicesRuralTechStoreRouteImport } from './routes/services.rural-tech-store'
import { Route as ServicesSaasSalesRouteImport } from './routes/services.saas-sales'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEducationalServicesRoute =
  ServicesEducationalServicesRouteImport.update({
    id: '/educational-services',
    path: '/educational-services',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLogisticsSalesRoute = ServicesLogisticsSalesRouteImport.update({
  id: '/logistics-sales',
  path: '/logistics-sales',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRuralTechStoreRoute = ServicesRuralTechStoreRouteImport.update({
  id: '/rural-tech-store',
  path: '/rural-tech-store',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSaasSalesRoute = ServicesSaasSalesRouteImport.update({
  id: '/saas-sales',
  path: '/saas-sales',
  getParentRoute: () => ServicesRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services/': typeof ServicesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services': typeof ServicesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services/': typeof ServicesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/partner'
    | '/services'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/partner'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/partner'
    | '/services'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PartnerRoute: typeof PartnerRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/educational-services': {
      id: '/services/educational-services'
      path: '/educational-services'
      fullPath: '/services/educational-services'
      preLoaderRoute: typeof ServicesEducationalServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/logistics-sales': {
      id: '/services/logistics-sales'
      path: '/logistics-sales'
      fullPath: '/services/logistics-sales'
      preLoaderRoute: typeof ServicesLogisticsSalesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rural-tech-store': {
      id: '/services/rural-tech-store'
      path: '/rural-tech-store'
      fullPath: '/services/rural-tech-store'
      preLoaderRoute: typeof ServicesRuralTechStoreRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/saas-sales': {
      id: '/services/saas-sales'
      path: '/saas-sales'
      fullPath: '/services/saas-sales'
      preLoaderRoute: typeof ServicesSaasSalesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesEducationalServicesRoute: typeof ServicesEducationalServicesRoute
  ServicesLogisticsSalesRoute: typeof ServicesLogisticsSalesRoute
  ServicesRuralTechStoreRoute: typeof ServicesRuralTechStoreRoute
  ServicesSaasSalesRoute: typeof ServicesSaasSalesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEducationalServicesRoute: ServicesEducationalServicesRoute,
  ServicesLogisticsSalesRoute: ServicesLogisticsSalesRoute,
  ServicesRuralTechStoreRoute: ServicesRuralTechStoreRoute,
  ServicesSaasSalesRoute: ServicesSaasSalesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PartnerRoute: PartnerRoute,
  ServicesRoute: ServicesRouteWithChildren,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
