/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesPolicyRouteImport } from './routes/cookies-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundsCancellationsRouteImport } from './routes/refunds-cancellations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ApiCancelRazorpayOrderRouteImport } from './routes/api/cancel-razorpay-order'
import { Route as ApiCreateRazorpayOrderRouteImport } from './routes/api/create-razorpay-order'
import { Route as ApiVerifyRazorpayPaymentRouteImport } from './routes/api/verify-razorpay-payment'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCustomerSupportRouteImport } from './routes/services.customer-support'
import { Route as ServicesDataEntryRouteImport } from './routes/services.data-entry'
import { Route as ServicesEducationalServicesRouteImport } from './routes/services.educational-services'
import { Route as ServicesLogisticsSalesRouteImport } from './routes/services.logistics-sales'
import { Route as ServicesMailSupportRouteImport } from './routes/services.mail-support'
import { Route as ServicesRuralTechStoreRouteImport } from './routes/services.rural-tech-store'
import { Route as ServicesSaasSalesRouteImport } from './routes/services.saas-sales'
import { Route as ApiPublicCancelRazorpayOrderRouteImport } from './routes/api/public/cancel-razorpay-order'
import { Route as ApiPublicCreateRazorpayOrderRouteImport } from './routes/api/public/create-razorpay-order'
import { Route as ApiPublicRegisterQrPaymentRouteImport } from './routes/api/public/register-qr-payment'
import { Route as ApiPublicVerifyRazorpayPaymentRouteImport } from './routes/api/public/verify-razorpay-payment'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesPolicyRoute = CookiesPolicyRouteImport.update({
  id: '/cookies-policy',
  path: '/cookies-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsCancellationsRoute = RefundsCancellationsRouteImport.update({
  id: '/refunds-cancellations',
  path: '/refunds-cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCancelRazorpayOrderRoute = ApiCancelRazorpayOrderRouteImport.update({
  id: '/api/cancel-razorpay-order',
  path: '/api/cancel-razorpay-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateRazorpayOrderRoute = ApiCreateRazorpayOrderRouteImport.update({
  id: '/api/create-razorpay-order',
  path: '/api/create-razorpay-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRazorpayPaymentRoute =
  ApiVerifyRazorpayPaymentRouteImport.update({
    id: '/api/verify-razorpay-payment',
    path: '/api/verify-razorpay-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomerSupportRoute = ServicesCustomerSupportRouteImport.update({
  id: '/customer-support',
  path: '/customer-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDataEntryRoute = ServicesDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEducationalServicesRoute =
  ServicesEducationalServicesRouteImport.update({
    id: '/educational-services',
    path: '/educational-services',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLogisticsSalesRoute = ServicesLogisticsSalesRouteImport.update({
  id: '/logistics-sales',
  path: '/logistics-sales',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMailSupportRoute = ServicesMailSupportRouteImport.update({
  id: '/mail-support',
  path: '/mail-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRuralTechStoreRoute = ServicesRuralTechStoreRouteImport.update({
  id: '/rural-tech-store',
  path: '/rural-tech-store',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSaasSalesRoute = ServicesSaasSalesRouteImport.update({
  id: '/saas-sales',
  path: '/saas-sales',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiPublicCancelRazorpayOrderRoute =
  ApiPublicCancelRazorpayOrderRouteImport.update({
    id: '/api/public/cancel-razorpay-order',
    path: '/api/public/cancel-razorpay-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateRazorpayOrderRoute =
  ApiPublicCreateRazorpayOrderRouteImport.update({
    id: '/api/public/create-razorpay-order',
    path: '/api/public/create-razorpay-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRegisterQrPaymentRoute =
  ApiPublicRegisterQrPaymentRouteImport.update({
    id: '/api/public/register-qr-payment',
    path: '/api/public/register-qr-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVerifyRazorpayPaymentRoute =
  ApiPublicVerifyRazorpayPaymentRouteImport.update({
    id: '/api/public/verify-razorpay-payment',
    path: '/api/public/verify-razorpay-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies-policy': typeof CookiesPolicyRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/cancel-razorpay-order': typeof ApiCancelRazorpayOrderRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/data-entry': typeof ServicesDataEntryRoute
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/mail-support': typeof ServicesMailSupportRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/cancel-razorpay-order': typeof ApiPublicCancelRazorpayOrderRoute
  '/api/public/create-razorpay-order': typeof ApiPublicCreateRazorpayOrderRoute
  '/api/public/register-qr-payment': typeof ApiPublicRegisterQrPaymentRoute
  '/api/public/verify-razorpay-payment': typeof ApiPublicVerifyRazorpayPaymentRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies-policy': typeof CookiesPolicyRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/cancel-razorpay-order': typeof ApiCancelRazorpayOrderRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/data-entry': typeof ServicesDataEntryRoute
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/mail-support': typeof ServicesMailSupportRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services': typeof ServicesIndexRoute
  '/api/public/cancel-razorpay-order': typeof ApiPublicCancelRazorpayOrderRoute
  '/api/public/create-razorpay-order': typeof ApiPublicCreateRazorpayOrderRoute
  '/api/public/register-qr-payment': typeof ApiPublicRegisterQrPaymentRoute
  '/api/public/verify-razorpay-payment': typeof ApiPublicVerifyRazorpayPaymentRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies-policy': typeof CookiesPolicyRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/cancel-razorpay-order': typeof ApiCancelRazorpayOrderRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/data-entry': typeof ServicesDataEntryRoute
  '/services/educational-services': typeof ServicesEducationalServicesRoute
  '/services/logistics-sales': typeof ServicesLogisticsSalesRoute
  '/services/mail-support': typeof ServicesMailSupportRoute
  '/services/rural-tech-store': typeof ServicesRuralTechStoreRoute
  '/services/saas-sales': typeof ServicesSaasSalesRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/cancel-razorpay-order': typeof ApiPublicCancelRazorpayOrderRoute
  '/api/public/create-razorpay-order': typeof ApiPublicCreateRazorpayOrderRoute
  '/api/public/register-qr-payment': typeof ApiPublicRegisterQrPaymentRoute
  '/api/public/verify-razorpay-payment': typeof ApiPublicVerifyRazorpayPaymentRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies-policy'
    | '/faq'
    | '/partner'
    | '/privacy-policy'
    | '/refunds-cancellations'
    | '/services'
    | '/terms-and-conditions'
    | '/api/cancel-razorpay-order'
    | '/api/create-razorpay-order'
    | '/api/verify-razorpay-payment'
    | '/services/customer-support'
    | '/services/data-entry'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/mail-support'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services/'
    | '/api/public/cancel-razorpay-order'
    | '/api/public/create-razorpay-order'
    | '/api/public/register-qr-payment'
    | '/api/public/verify-razorpay-payment'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies-policy'
    | '/faq'
    | '/partner'
    | '/privacy-policy'
    | '/refunds-cancellations'
    | '/terms-and-conditions'
    | '/api/cancel-razorpay-order'
    | '/api/create-razorpay-order'
    | '/api/verify-razorpay-payment'
    | '/services/customer-support'
    | '/services/data-entry'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/mail-support'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services'
    | '/api/public/cancel-razorpay-order'
    | '/api/public/create-razorpay-order'
    | '/api/public/register-qr-payment'
    | '/api/public/verify-razorpay-payment'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies-policy'
    | '/faq'
    | '/partner'
    | '/privacy-policy'
    | '/refunds-cancellations'
    | '/services'
    | '/terms-and-conditions'
    | '/api/cancel-razorpay-order'
    | '/api/create-razorpay-order'
    | '/api/verify-razorpay-payment'
    | '/services/customer-support'
    | '/services/data-entry'
    | '/services/educational-services'
    | '/services/logistics-sales'
    | '/services/mail-support'
    | '/services/rural-tech-store'
    | '/services/saas-sales'
    | '/services/'
    | '/api/public/cancel-razorpay-order'
    | '/api/public/create-razorpay-order'
    | '/api/public/register-qr-payment'
    | '/api/public/verify-razorpay-payment'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesPolicyRoute: typeof CookiesPolicyRoute
  FaqRoute: typeof FaqRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundsCancellationsRoute: typeof RefundsCancellationsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiCancelRazorpayOrderRoute: typeof ApiCancelRazorpayOrderRoute
  ApiCreateRazorpayOrderRoute: typeof ApiCreateRazorpayOrderRoute
  ApiVerifyRazorpayPaymentRoute: typeof ApiVerifyRazorpayPaymentRoute
  ApiPublicCancelRazorpayOrderRoute: typeof ApiPublicCancelRazorpayOrderRoute
  ApiPublicCreateRazorpayOrderRoute: typeof ApiPublicCreateRazorpayOrderRoute
  ApiPublicRegisterQrPaymentRoute: typeof ApiPublicRegisterQrPaymentRoute
  ApiPublicVerifyRazorpayPaymentRoute: typeof ApiPublicVerifyRazorpayPaymentRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies-policy': {
      id: '/cookies-policy'
      path: '/cookies-policy'
      fullPath: '/cookies-policy'
      preLoaderRoute: typeof CookiesPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds-cancellations': {
      id: '/refunds-cancellations'
      path: '/refunds-cancellations'
      fullPath: '/refunds-cancellations'
      preLoaderRoute: typeof RefundsCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cancel-razorpay-order': {
      id: '/api/cancel-razorpay-order'
      path: '/api/cancel-razorpay-order'
      fullPath: '/api/cancel-razorpay-order'
      preLoaderRoute: typeof ApiCancelRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-razorpay-order': {
      id: '/api/create-razorpay-order'
      path: '/api/create-razorpay-order'
      fullPath: '/api/create-razorpay-order'
      preLoaderRoute: typeof ApiCreateRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-razorpay-payment': {
      id: '/api/verify-razorpay-payment'
      path: '/api/verify-razorpay-payment'
      fullPath: '/api/verify-razorpay-payment'
      preLoaderRoute: typeof ApiVerifyRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/customer-support': {
      id: '/services/customer-support'
      path: '/customer-support'
      fullPath: '/services/customer-support'
      preLoaderRoute: typeof ServicesCustomerSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data-entry': {
      id: '/services/data-entry'
      path: '/data-entry'
      fullPath: '/services/data-entry'
      preLoaderRoute: typeof ServicesDataEntryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/educational-services': {
      id: '/services/educational-services'
      path: '/educational-services'
      fullPath: '/services/educational-services'
      preLoaderRoute: typeof ServicesEducationalServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/logistics-sales': {
      id: '/services/logistics-sales'
      path: '/logistics-sales'
      fullPath: '/services/logistics-sales'
      preLoaderRoute: typeof ServicesLogisticsSalesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mail-support': {
      id: '/services/mail-support'
      path: '/mail-support'
      fullPath: '/services/mail-support'
      preLoaderRoute: typeof ServicesMailSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rural-tech-store': {
      id: '/services/rural-tech-store'
      path: '/rural-tech-store'
      fullPath: '/services/rural-tech-store'
      preLoaderRoute: typeof ServicesRuralTechStoreRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/saas-sales': {
      id: '/services/saas-sales'
      path: '/saas-sales'
      fullPath: '/services/saas-sales'
      preLoaderRoute: typeof ServicesSaasSalesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/public/cancel-razorpay-order': {
      id: '/api/public/cancel-razorpay-order'
      path: '/api/public/cancel-razorpay-order'
      fullPath: '/api/public/cancel-razorpay-order'
      preLoaderRoute: typeof ApiPublicCancelRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-razorpay-order': {
      id: '/api/public/create-razorpay-order'
      path: '/api/public/create-razorpay-order'
      fullPath: '/api/public/create-razorpay-order'
      preLoaderRoute: typeof ApiPublicCreateRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register-qr-payment': {
      id: '/api/public/register-qr-payment'
      path: '/api/public/register-qr-payment'
      fullPath: '/api/public/register-qr-payment'
      preLoaderRoute: typeof ApiPublicRegisterQrPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-razorpay-payment': {
      id: '/api/public/verify-razorpay-payment'
      path: '/api/public/verify-razorpay-payment'
      fullPath: '/api/public/verify-razorpay-payment'
      preLoaderRoute: typeof ApiPublicVerifyRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCustomerSupportRoute: typeof ServicesCustomerSupportRoute
  ServicesDataEntryRoute: typeof ServicesDataEntryRoute
  ServicesEducationalServicesRoute: typeof ServicesEducationalServicesRoute
  ServicesLogisticsSalesRoute: typeof ServicesLogisticsSalesRoute
  ServicesMailSupportRoute: typeof ServicesMailSupportRoute
  ServicesRuralTechStoreRoute: typeof ServicesRuralTechStoreRoute
  ServicesSaasSalesRoute: typeof ServicesSaasSalesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCustomerSupportRoute: ServicesCustomerSupportRoute,
  ServicesDataEntryRoute: ServicesDataEntryRoute,
  ServicesEducationalServicesRoute: ServicesEducationalServicesRoute,
  ServicesLogisticsSalesRoute: ServicesLogisticsSalesRoute,
  ServicesMailSupportRoute: ServicesMailSupportRoute,
  ServicesRuralTechStoreRoute: ServicesRuralTechStoreRoute,
  ServicesSaasSalesRoute: ServicesSaasSalesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesPolicyRoute: CookiesPolicyRoute,
  FaqRoute: FaqRoute,
  PartnerRoute: PartnerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundsCancellationsRoute: RefundsCancellationsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiCancelRazorpayOrderRoute: ApiCancelRazorpayOrderRoute,
  ApiCreateRazorpayOrderRoute: ApiCreateRazorpayOrderRoute,
  ApiVerifyRazorpayPaymentRoute: ApiVerifyRazorpayPaymentRoute,
  ApiPublicCancelRazorpayOrderRoute: ApiPublicCancelRazorpayOrderRoute,
  ApiPublicCreateRazorpayOrderRoute: ApiPublicCreateRazorpayOrderRoute,
  ApiPublicRegisterQrPaymentRoute: ApiPublicRegisterQrPaymentRoute,
  ApiPublicVerifyRazorpayPaymentRoute: ApiPublicVerifyRazorpayPaymentRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
